### ISSUE TITLE
bug: Browsers stuck on loading Unicorn assets.

### ISSUE THREAD

**Issue by BeatriceMitchell** [VeryGoodOpenSource/very_good_ranch#222]
Certain browsers are unable to load the unicorn assets, and get stuck on the initial loading screen.

On Mobile: Brave (iOS), DuckDuckGo (iOS), Chrome (iOS)
On Desktop: Brave
Tablets are encountering issues as well.

**Comment by jxstxn1** [comment]
Can reproduce, same thing applies for Safari on IOS
